### ISSUE TITLE
Create KOTLIN template for RIT CREATE FORMULA command

### ISSUE THREAD

**Issue by victor-schumacher** [ZupIT/ritchie-formulas#111]
### Premisse

- You'll find everything there is to know about the template structure to follow here: https://github.com/ZupIT/ritchie-formulas/tree/master/templates/create_formula

### Suggestion

- It would be great if this template match the rit demo hello-world formula (coded in GO) : https://github.com/ZupIT/ritchie-formulas/tree/master/demo/hello-world with the same inputs and the same display.

### Why is it needed ?

- It will make it easier for programmers to create formulas in Kotlin.

**Comment by Clevisson** [comment]
Quero pegar essa issue!

**Comment by GuillaumeFalourd** [comment]
Hi @Clevisson , sure ! I've assigned it to you. Thank you for contributing 👍

**Comment by jSAMUELj** [comment]
@GuillaumeFalourd Hi! As you told me to leave message under this ISSUE, so can you assign this to me? 
I have already started working on it and have some code done

**Comment by GuillaumeFalourd** [comment]
Great @jSAMUELj , I've assigned it to you as well 👍🏼 
Thank you for contributing 🚀

**Comment by fabianofernandeszup** [comment]
Issue prioritized by the Adoption team

**Comment by fabianofernandeszup** [comment]
Solved
