### ISSUE TITLE
[FEATURE] Awesome list for repos

### ISSUE THREAD

**Issue by rasouza** [ZupIT/ritchie-formulas#125]
**What would you like to be added**:
Have you guys considered creating an Awesome List for different ritchie formula repos?
**Why is this needed**:
Since your repo management is not centralized, which is good, we could maintain a curated list so users could submit (through PRs) and search for formulas there.

Ideally, since you would be the ones to assessing if the formula is actually good enough or not to be accepted in the list, you should be the owners and contributors of this repo/list, but if you're not very sure how to do this I can prepare a valid one and include you as official contributors.

I'm glad to hear your opinion on top of that before taking into action

**Comment by fabianofernandeszup** [comment]
@rasouza Soon we will launch the portal with an official repository of community formulas, such as an npm, docker hub, etc. The portal is already ready and we are making some adjustments taking into account the recently released version 2 of the repository.
As soon as we launch we’d love your opinion of him. Thank you for your interest.

**Comment by rasouza** [comment]
Great! Let's close it then
