### ISSUE TITLE
[BUG] Credentials in are presented in plain text when presenting an error

### ISSUE THREAD

**Issue by brunats** [ZupIT/ritchie-formulas#154]
**What happened**:
When using the github credentials to create a repository (rit github create repo) and the process happens an authentication error they are presented in plain text next to the error.

> ![Captura de tela de 2020-08-26 15-56-00](https://user-images.githubusercontent.com/14079465/91345027-22f80d80-e7b5-11ea-9916-53165f7b1162.png)

**What you expected to happen**:
Display an authentication error with the credentials, but without writing them, but I don't know if this is a bug or expected behavior.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
rit set credential # usign user: testUser, email: testEmail and password: testPassword
rit github create repo # using an private repo
```

**Anything else we need to know?**:

**Environment**:

- Ritchie version: 2.0.4

- Operating System: Ubuntu 18.04.5 LTS
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by GuillaumeFalourd** [comment]
Hi @brunats , thank you for opening this ISSUE.

I checked the code and this log is from the GITHUB API service.

When it's a bad credentials error, informing the user of the datas used to call the service can actually help to identify the error. 

We can check with @joaorufinozup if it's what he wanted to do. I personally find it useful.

**Comment by joaorufinozup** [comment]
Hi @brunats, as @GuillaumeFalourd said, this log is from the GITHUB API, and I think it is useful to identify the error because it is easier to see what is the wrong credential.

**Comment by GuillaumeFalourd** [comment]
@brunats We understood it wasn't an error, but the desired behavior when running these formulas. That's the reason why I will close this ISSUE. Thank you for your suggestion !
