### ISSUE TITLE
[FORMULA] Create new generic formulas

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#183]
### What would you like ?

Create a new generic formula for the community, manipulating any tool to create new use cases using Ritchie. 

It can be anything that make sense to you, using API or creating something based on existing scripts. From Twitter to Google Cloud Platform, Selenium, Vault, Jira... everything is possible, you can be creative! 👍 

_Note: It would be great to be able to execute the formula through Docker, and to make it works on any OS._

### Why is it needed ?

To show the community what the product offers and how it can resolve different kinds of problems.

### Recommendation

Contribute opening one Pull Request for each formula .
This issue can be assigned to more than one collaborator, just leave a comment here.

- [X] Formula 1
- [ ] Formula 2
- [ ] Formula 3
- [ ] Formula 4
- [ ] Formula 5
- [ ] Formula 6
- [ ] Formula 7
- [ ] Formula 8
- [ ] Formula 9
- [ ] Formula 10

**Comment by fabianofernandeszup** [comment]
@GuillaumeFalourd Can we close this issue ?

**Comment by GuillaumeFalourd** [comment]
No problem, I'll close it 👍🏼
