### ISSUE TITLE
Create TYPESCRIPT template for RIT CREATE FORMULA command

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#184]
### Premisse

- You'll find everything there is to know about the template structure to follow here: https://github.com/ZupIT/ritchie-formulas/tree/master/templates/create_formula

### Suggestion

- It would be great if this template match the rit demo hello-world formula (coded in GO) : https://github.com/ZupIT/ritchie-formulas/tree/master/demo/hello-world with the same inputs and the same display.

### Why is it needed ?

- It will make it easier for programmers to create formulas in Typescript.

**Comment by brunonmelo** [comment]
Hello everyone.
I would like to address this issue.

**Comment by GuillaumeFalourd** [comment]
Sure, I've assigned it to you @brunonmelo . Thank you for contributing ! 👍

**Comment by brunonmelo** [comment]
I pushed a new Merge Request to be reviewed.
#243

**Comment by brunonmelo** [comment]
I opened a new pull request for the hacktoberfest
#254
