### ISSUE TITLE
Update RIT AWS CLEAN BUCKET formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#197]
### What would you like ?

- I would the **RIT AWS CLEAN BUCKET** formula to have a complete README file explaining what the formula does, with an example of its execution (GIF).

- Formula : https://github.com/ZupIT/ritchie-formulas/tree/master/aws/clean/bucket

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repov

**Comment by ng29** [comment]
Hey @GuillaumeFalourd

I would like to work on this , if available for grabs?

**Comment by GuillaumeFalourd** [comment]
It's all yours @ng29 , thank your for contributing 🚀
