### ISSUE TITLE
Update RIT AWS CREATE BUCKET formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#198]
### What would you like ?

- I would the **RIT AWS CREATE BUCKET** formula to have a complete README file explaining what the formula does, with an example of its execution (GIF).

- Formula : https://github.com/ZupIT/ritchie-formulas/tree/master/aws/create/bucket

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repo

**Comment by ng29** [comment]
Hey @GuillaumeFalourd 

I would like to work on this as I recently started AWS , so please provide more info on this..

**Comment by GuillaumeFalourd** [comment]
Hi @ng29 ! Thank you for contributing 🚀 

To update the README file you'll have to [install Ritchie on your computer](https://docs.ritchiecli.io/getting-started/installation) and initialize Ritchie accepting to add the `commons` repository (which is this github repo).

Once you've done it, just execute the `rit aws create bucket` command (you'll need to inform AWS credentials first) and you'll see the result.

Feel free to ask if you have any question 👍

**Comment by ng29** [comment]
> Hi @ng29 ! Thank you for contributing 🚀
> 
> To update the README file you'll have to [install Ritchie on your computer](https://docs.ritchiecli.io/getting-started/installation) and initialize Ritchie accepting to add the `commons` repository (which is this github repo).
> 
> Once you've done it, just execute the `rit aws create bucket` command (you'll need to inform AWS credentials first) and you'll see the result.
> 
> Feel free to ask if you have any question 👍

Sure @GuillaumeFalourd , will initiate the process

**Comment by ng29** [comment]
> Hi @ng29 ! Thank you for contributing 🚀
> 
> To update the README file you'll have to [install Ritchie on your computer](https://docs.ritchiecli.io/getting-started/installation) and initialize Ritchie accepting to add the `commons` repository (which is this github repo).
> 
> Once you've done it, just execute the `rit aws create bucket` command (you'll need to inform AWS credentials first) and you'll see the result.
> 
> Feel free to ask if you have any question 👍

Hey @GuillaumeFalourd ,
I have installed ritchie on local , could you please guide me how to initialize it accepting comms repo and where aws creds need to be configured ?? 

And I just saw https://insights.zup.com.br/hacktoberfest , so am I eligible for this  ?? 

Cheers.

**Comment by GuillaumeFalourd** [comment]
Hi @ng29 ,

Everything about the initialization is on the documentation [here](https://docs.ritchiecli.io/getting-started/initialization)
Feel free to ask anything if necessary.

Regarding the credentials, you can add them using the `rit set credential` command. Otherwise, executing the aws command locally (you'll need Golang install) should ask them to you if not set yet.

**Comment by ng29** [comment]
> Hi @ng29 ,
> 
> Everything about the initialization is on the documentation [here](https://docs.ritchiecli.io/getting-started/initialization)
> Feel free to ask anything if necessary.
> 
> Regarding the credentials, you can add them using the `rit set credential` command. Otherwise, executing the aws command locally (you'll need Golang install) should ask them to you if not set yet.
> 
> Regarding the ZupIT challenge, unfortunately you won't be able to participate this year, as our company will only send swags to contributors from Brazil. However, as we received many PR from other countries, we'll probably change this for 2021.

Hey @GuillaumeFalourd ,

Thanks for the information, I carried out the above steps but failed in creating a bucket due to some error shown below.
And i have added aws creds by chosing type and entering aws id and password into it, i reckon thats correct way ? ?

$ rit list credential
PROVIDER	CONTEXT	CREDENTIAL                                                         
aws     	default	{"accesskeyid":"*******...","secretaccesskey":"Cosmo********"}
$ rit aws create bucket
Error: failed building formula with Makefile, verify your repository
More about error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

PLease help me in resolving this issue so that i can proceed 👍 

Cheers

**Comment by GuillaumeFalourd** [comment]
Hi @ng29 , it's seems this the problem is due to not having MacOS developer tools installed on your computer. Take a look a [this article](https://ma.ttias.be/mac-os-xcrun-error-invalid-active-developer-path-missing-xcrun/) and let me know if it resolve you issue.

**Comment by ng29** [comment]
> Hi @ng29 , it's seems this the problem is due to not having MacOS developer tools installed on your computer. Take a look a [this article](https://ma.ttias.be/mac-os-xcrun-error-invalid-active-developer-path-missing-xcrun/) and let me know if it resolve you issue.

Thanks for the link, but it also failed with error " NOT AVAILABLE FROM SOFTWARE UPDATE SERVER"
So trying to install manually via dev website.

**Comment by GuillaumeFalourd** [comment]
@ng29 : I believe the current problem is that you need the `make` command installed to be able to execute the scripts on the formula `Makefile`. Generally this command come with the Developper Tools for MacOS (Xcode) but it may be different depending on the version you're using.

I would recommend to follow the steps suggested on this [stackoverflow issue](https://stackoverflow.com/questions/10265742/how-to-install-make-and-gcc-on-a-mac) and see if the Makefile error still persists afterwards.

**Comment by ng29** [comment]
> @ng29 : I believe the current problem is that you need the `make` command installed to be able to execute the scripts on the formula `Makefile`. Generally this command comes with the Developer Tools for MacOS (Xcode) but it may be different depending on the version you're using.
> 
> I would recommend to follow the steps suggested on this [stackoverflow issue](https://stackoverflow.com/questions/10265742/how-to-install-make-and-gcc-on-a-mac) and see if the Makefile error still persists afterwards.

Hey @GuillaumeFalourd , i completely forgot about this issue as got stuck with other tasks and facing some health issues too recently, so apologies and will try to contribute in the near future.

Cheers

**Comment by GuillaumeFalourd** [comment]
No problem @ng29 ! Thank you for your contributions on the other ISSUES 👍🏼 

As it's the last day to contribute for the Hacktoberfest, we organised a HackDay here and people are working on different issues before the end of the day 😄

**Comment by ng29** [comment]
> No problem @ng29 ! Thank you for your contributions on the other ISSUES 👍🏼
> 
> As it's the last day to contribute for the Hacktoberfest, we organised a HackDay here and people are working on different issues before the end of the day 😄

Thanks @GuillaumeFalourd for understanding.
Ahh, gotchaaa, wonderful initiative and will be rocking in the next Hacktoberfest..

Cheers
