### ISSUE TITLE
Update RIT AWS GENERATE TERRAFORM-PROJECT formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#200]
### What would you like ?

- I would the **RIT AWS GENERATE TERRAFORM-PROJECT** formula to have a complete README file explaining what the formula does, with an example of its execution (GIF).

- Formula : https://github.com/ZupIT/ritchie-formulas/tree/master/aws/generate/terraform-project

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repo

**Comment by eduardorcury** [comment]
Hello! Can I take this issue?

**Comment by GuillaumeFalourd** [comment]
I've assigned it to you @eduardorcury , thank you for contributing 👍🏼
