### ISSUE TITLE
Update RIT AWS LIST BUCKET formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#201]
### What would you like ?

- I would the **RIT AWS LIST BUCKET** formula to have a complete README file explaining what the formula does, with an example of its execution (GIF).

- Formula : https://github.com/ZupIT/ritchie-formulas/tree/master/aws/list/bucket

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repo

**Comment by ng29** [comment]
Hey @GuillaumeFalourd

I would like to work on this if it is available for grabs ??

**Comment by GuillaumeFalourd** [comment]
Hi @ng29 , it's definitely available! I'll assign it to you 👍 

Feel free to ask anything if you have any question 😄

**Comment by ng29** [comment]
> Hi @ng29 , it's definitely available! I'll assign it to you 👍
> 
> Thank you for contributing 🚀
> 
> Feel free to ask anything if you have any question 😄

Sure @GuillaumeFalourd , i will give it a look and will come back to you in case of queries.

Cheers

**Comment by isaiastavares** [comment]
@GuillaumeFalourd can assign this issue to me, pls ?

**Comment by GuillaumeFalourd** [comment]
Hmm, i'm know seeing that @ng29 was working on this issue but that I already approved @isaiastavares PR for updating the file.
Feel free to work on this issue @ng29 , improving what @isaiastavares has done. Or to work on another one if you wish.

Sorry about the misunderstanding 😨

**Comment by ng29** [comment]
> Hmm, i'm know seeing that @ng29 was working on this issue but that I already approved @isaiastavares PR for updating the file.
> Feel free to work on this issue @ng29 , improving what @isaiastavares has done. Or to work on another one if you wish.
> 
> Sorry about the misunderstanding 😨

No worries pal @isaiastavares  can work on this as i am struggling with setup part so show must go on.. I will work on other ones
