### ISSUE TITLE
Update RIT GITHUB NAVIGATE HANDBOOK formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#214]
### What would you like ?

- I would the **RIT GITHUB NAVIGATE HANDBOOK** formula to have a complete README file explaining what the formula does, with an example of its execution (the actual GIF isn't accurate).

- Formula : https://github.com/ZupIT/ritchie-formulas/tree/master/github/navigate/handbook

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repo

**Comment by isaiastavares** [comment]
@GuillaumeFalourd can assign this issue to me, pls ? I already created the PR #294
