### ISSUE TITLE
Update RIT GITHUB SEARCH HANDBOOK formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#215]
### What would you like ?

- I would the **RIT GITHUB SEARCH HANDBOOK** formula to have a complete README file explaining what the formula does, with an example of its execution (GIF).

- Formula : https://github.com/ZupIT/ritchie-formulas/tree/master/github/search/handbook

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repo

**Comment by denisvieira05** [comment]
Hi @GuillaumeFalourd , this issue is only to update formula documentation based on example templates ? I update the same file and path to this ?

**Comment by GuillaumeFalourd** [comment]
Hi @denisvieira05 , yes, this issue consists in updating only that file.

Depending on the contents added on the README file, you'll maybe have to add image ou videos files as well, but it's not mandatory (or can be done online).

Feel free to ask anything if you have questions 👍

**Comment by denisvieira05** [comment]
> Hi @denisvieira05 , yes, this issue consists in updating only that file.
> 
> Depending on the contents added on the README file, you'll maybe have to add image ou videos files as well, but it's not mandatory (or can be done online).
> 
> Would you like to do it ? 
> 
> Feel free to ask anything if you have questions

Ok @GuillaumeFalourd , thank you !! you can assign to me ?

**Comment by GuillaumeFalourd** [comment]
Done @denisvieira05 👍 
Thank you for contributing 🚀

**Comment by denisvieira05** [comment]
@GuillaumeFalourd I had problems to execute the formula, I don't understand the objective 

 I prefer contribute with others

**Comment by GuillaumeFalourd** [comment]
No problem @denisvieira05 👍 

But before anything, let me explain you how it works.

The execution should return something like this:

<img width="694" alt="Screen Shot 2020-10-13 at 09 09 50" src="https://user-images.githubusercontent.com/22433243/95858798-0481ad80-0d34-11eb-8a69-9dc8c0a6bbe2.png">

And after selecting a class, it would return the class implementation to the user:

<img width="920" alt="Screen Shot 2020-10-13 at 09 10 24" src="https://user-images.githubusercontent.com/22433243/95858827-12cfc980-0d34-11eb-8689-938c24bbd7f3.png">

Let me know if with this explanation you still want to contribute to this issue or not, ok ? 😄

**Comment by denisvieira05** [comment]
I understand @GuillaumeFalourd , thank you for you help !! I will contribute with this !!
