### ISSUE TITLE
Update RIT GITHUB UPDATE FORK formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#216]
### What would you like ?

- I would the **RIT GIT UPDATE FORK** formula to have a complete README file explaining what the formula does, with an example of its execution (the current GIF isn't accurate).

- Formula : https://github.com/ZupIT/ritchie-formulas/tree/master/git/update/fork

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repo

**Comment by fabianofernandeszup** [comment]
Issue prioritized by the Adoption team

**Comment by fabianofernandeszup** [comment]
Solved
