### ISSUE TITLE
Update RIT SCAFFOLD GENERATE SPRING-STARTER formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#227]
### What would you like ?

- I would the **RIT SCAFFOLD GENERATE SPRING-STARTER** formula to have a complete README file explaining what the formula does, with an example of its execution (GIF).

- Formula : https://github.com/ZupIT/ritchie-formulas/tree/master/scaffold/generate/spring-starter

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repo

**Comment by denisvieira05** [comment]
@GuillaumeFalourd can assign this issue to me ? 

I already created the PR https://github.com/ZupIT/ritchie-formulas/pull/271

**Comment by GuillaumeFalourd** [comment]
Hi Denis, done it. Thank you for contributing 👍
