### ISSUE TITLE
Update RIT SCAFFOLD SHOW SPRING-STARTER-DEPENDENCIES formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#228]
### What would you like ?

- I would the **RIT SCAFFOLD SHOW SPRING-STARTER-DEPENDENCIES** formula to have a complete README file explaining what the formula does, with an example of its execution (GIF).

- Formula : https://github.com/ZupIT/ritchie-formulas/tree/master/scaffold/show/spring-starter-dependencies

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repo

**Comment by isaiastavares** [comment]
@GuillaumeFalourd can assign this issue to me, pls ?

**Comment by isaiastavares** [comment]
I already created the PR #283
