### ISSUE TITLE
Add tutorial field in config.json

### ISSUE THREAD

**Issue by lucasdittrichzup** [ZupIT/ritchie-formulas#251]
**What would you like to be added**:

With the new `tutorial field` added to the `config.json` file, it is interesting to adjust the formulas of the commons to adopt them in their respective files

**Why is this needed**:

Make the existing formulas compatible by adding the `tutorial field` in the inputs.

**Comment by caioeverest** [comment]
Hi! 
I open a PR addressing this issue: https://github.com/ZupIT/ritchie-formulas/pull/253
