### ISSUE TITLE
Add required field in config.json 

### ISSUE THREAD

**Issue by lucasdittrichzup** [ZupIT/ritchie-formulas#252]
**What would you like to be added**:

With the new `required field` added to the `config.json` file, it is interesting to adjust the formulas of the commons to adopt them in their respective files

**Why is this needed**:

Make the existing formulas compatible by adding the `required field` in the inputs.

*Edit*

**Tasks**:

- [ ] Formulas group
- [ ] Tasks

**Comment by CptOrange16** [comment]
I could take this one

**Comment by GuillaumeFalourd** [comment]
Sure, I've assigned it to you @CptOrange16 
Thank you for contributing ! 👍

**Comment by CptOrange16** [comment]
@lucasdittrichzup @GuillaumeFalourd thank you for letting me help. 
Can you help me understand exactly what needs to be done?
When you say:
> With the new required field added to the config.json file, it is interesting to adjust the formulas of the commons to adopt them in their respective files
do you mean the tutorial field?

If so, how exactly would I introduce the tutorial field in the formulas?

**Comment by GuillaumeFalourd** [comment]
Sure @CptOrange16 👍 

You'll have to update the config.json file of each formula inside the repository, and add the `required` field to each input set in the file.

You can find more informations on the [documentation here](https://docs.ritchiecli.io/tutorials/formulas/implement-a-formula)

**Comment by CptOrange16** [comment]
@GuillaumeFalourd hello, i've added the required field to the config.json files. 
I wasn't sure what to write on the value so i wrote:

     "required": "Select true or false for this field."
If you want me to change that for any other value just let me know

**Comment by GuillaumeFalourd** [comment]
This field is a boolean value @CptOrange16 , so actually it's you who will have to inform if the inputs are required true or false.

**Comment by CptOrange16** [comment]
> 
> 
> This field is a boolean value @CptOrange16 , so actually it's you who will have to inform if the inputs are required true or false.
> 
> ex: `"required": true`

Aha yes thank you, that was what i was having doubts on. I'll get right on fixing that
