### ISSUE TITLE
Update Node.js Hello World template

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#257]
### Context

*Edit: Ritchie CLI is an open source product that allows you to create, store and share any kind of automations, executing them through command lines, to run operations or start workflows.*

*Edit: Those automations are based on those templates, and we want to update the old ones to match the new template we already implemented in go. To do so it will be necessary to update 3 files from this template, the config.json, the main class and the formula class. All those files are located here: https://github.com/ZupIT/ritchie-formulas/tree/master/templates/create_formula/languages*

### What do you want ?

- Update the Node hello-world templates to match the **rit demo hello-world formula** : https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world with the same inputs and the same display.

### Why is this needed ?

- It would help the Node programmer to have a template with an example of each kind of inputs available with Ritchie.

- It would also help with Ritchie first contact as the demo formula (rit demo hello-world) will be the first formula executed by many users (following the documentation: https://docs.ritchiecli.io/how-to/how-to-run-formulas/commands)

**Comment by prateek1998** [comment]
I can help you in this but can you provide more description and also above link is not working .
_

**Comment by GuillaumeFalourd** [comment]
Hi @prateek1998 , thank you for the message.
I updated the link, it was referring at the wrong repository.

Ritchie CLI is an open source product that allows you to create, store and share any kind of automations, executing them through command lines, to run operations or start workflows.

Those automations are based on those templates, and we want to update the old ones to match the new template we already implemented in go. To do so it will be necessary to update 3 files from this template, the config.json, the index.js and the formula.js.

All those files are located here: https://github.com/ZupIT/ritchie-formulas/tree/master/templates/create_formula/languages/node

**Comment by jSAMUELj** [comment]
Hi! Is this still open ?

**Comment by GuillaumeFalourd** [comment]
Hi @jSAMUELj , thank you for the message 👍🏼 

The ISSUE has actually been closed with this PR: https://github.com/ZupIT/ritchie-formulas/pull/267/files

And we didn't check it, sorry for that...

But we still have a lot of ISSUES open, have a look! 😄

**Comment by jSAMUELj** [comment]
@GuillaumeFalourd no problem. 

I found more similar issues like this one but for another languages like: PHP, Python3 and Powershell. 
Are they also closed or is there one opened ?

**Comment by GuillaumeFalourd** [comment]
Those 3 have people assigned on them, therefore without any return from them I wouldn't suggest to assign them to someone else.

If you wish, we still need 3 templates to create: KOTLIN, PERL and SWIFT. And a lot of README files aren't updated. 
You could also create a formula form scratch, here or on the [ritchie-formulas-demo](https://github.com/ZupIT/ritchie-formulas-demo) repository, to participate the challenge 😃

**Comment by jSAMUELj** [comment]
@GuillaumeFalourd OK, can I try to create KOTLIN template?

**Comment by GuillaumeFalourd** [comment]
Sure @jSAMUELj , leave a message on the Kotlin ISSUE please (to keep things on the right place) and follow [this guide](https://github.com/ZupIT/ritchie-formulas/tree/master/templates/create_formula) to create the new template 👍🏼
