### ISSUE TITLE
Update Shell Hello World template

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#259]
### Context

- Ritchie CLI is an open source product that allows you to create, store and share any kind of automations, executing them through command lines, to run operations or start workflows.

- Those automations are based on those templates, and we want to update the old ones to match the new template we already implemented in go. To do so it will be necessary to update 3 files from this template, the config.json, the main class and the formula class. All those files are located here: https://github.com/ZupIT/ritchie-formulas/tree/master/templates/create_formula/languages

### What do you want ?

- Update the Shell hello-world templates to match the **rit demo hello-world formula** : https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world with the same inputs and the same display.

### Why is this needed ?

- It would help the Shell programmer to have a template with an example of each kind of inputs available with Ritchie.

- It would also help with Ritchie first contact as the demo formula (rit demo hello-world) will be the first formula executed by many users (following the documentation: https://docs.ritchiecli.io/how-to/how-to-run-formulas/commands)

**Comment by senoja** [comment]
May I submit an MR for this?

**Comment by GuillaumeFalourd** [comment]
Sure @senoja , I'll assign you the issue. Thank you for contributing 👍🏼
