### ISSUE TITLE
Update README files

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas#260]
## What do we need ?

- We currently have more than 30 ISSUES to update README files of specific automation created on ritchie-cli.
- You can find them here : https://github.com/ZupIT/ritchie-formulas/issues?q=is%3Aissue+is%3Aopen+update+readme

## A good opportunity to discover a new tool and participate to the Hacktoberfest event

- All of the ISSUES above are labelled `good-first-issue` because you simply have to install the tool, and then executing the command to be able to update the formula README.md file afterwards with new datas.

## Details

- Comment on the issue you want to work with (on the list above) for our team to assign it to you 👍 
- We would be happy to discuss the tool with you if you have any question / suggestion or feedback.

*Note: We have other similar issues for the hacktoberfest here: https://github.com/ZupIT/ritchie-formulas-demo/issues*

**Comment by Vortex2wenty** [comment]
Hi, I would like to work on this issue. Thanks.

**Comment by fabianofernandeszup** [comment]
Can we close these issues?

**Comment by GuillaumeFalourd** [comment]
No problem, I'll close it 👍🏼
