### ISSUE TITLE
Add Docker implementation on RIT AWS APPLY TERRAFORM formula

### ISSUE THREAD

**Issue by eduardorcury** [ZupIT/ritchie-formulas#276]
## What would you like to be added:

- I would like to be able to run the **RIT AWS APPLY TERRAFORM** formula using Docker.

## Why is this needed:

- The **AWS APPLY TERRAFORM** formula was implemented without the Dockerfile, so this funcionality has to be implemented for this formula to match the other ones and allow the user to run it using Docker.

**Comment by GuillaumeFalourd** [comment]
I've assigned you the ISSUE @eduardorcury , as we discussed here: https://github.com/ZupIT/ritchie-formulas/pull/272 👍

**Comment by eduardorcury** [comment]
I've managed to create the Dockerfile and make the necessary changes on Makefile. It seems like the Docker image was built successfully, but i'm getting an error when the formula tries to run the terraform commands.

![image](https://user-images.githubusercontent.com/60987061/96048157-37b36200-0e44-11eb-88b0-b16ea4d054ad.png)

When I removed the execution of terraform version in the formula, the command successfully clonned the repository given in the input, but failed latter when running terraform init, which makes me think the problem is with the terraform commands.

Running *terraform -version* and *rit aws apply terraform* locally works fine.

As you can see, I get no error messages, which makes it harder to debug. Any ideas on how to solve this would be much appreciated! :smile:

**Comment by GuillaumeFalourd** [comment]
@eduardorcury , to make the terraform command works on Docker, I believe it will be necessary to install terraform on the container. The same way it's done for Ritchie for example here: https://github.com/ZupIT/ritchie-formulas/blob/master/templates/create_formula/languages/go/Dockerfile
