### ISSUE TITLE
Update RUBY Hello World template

### ISSUE THREAD

**Issue by fabianofernandeszup** [ZupIT/ritchie-formulas#303]
### What do you want ?

- Update the RUBY hello-world templates to match the **rit demo hello-world formula** : https://github.com/ZupIT/ritchie-formulas/tree/master/demo/hello-world with the same inputs and the same display.

### Why is this needed ?

- It would help the RUBY programmer to have a template with an example of each kind of inputs available with Ritchie.

- It would also help with Ritchie first contact as the demo formula (rit demo hello-world) will be the first formula executed by many users (following the documentation: https://docs.ritchiecli.io/how-to/how-to-run-formulas/commands)

**Comment by chiaretto** [comment]
I just uploaded a PR for this issue.
